### ISSUE TITLE
Failed at task 'TASK [ansible-service-broker CR state=present]'

### ISSUE THREAD

**Issue by zihantang-rh** [fusor/catbrokers4#16]
When I run the playbook to install svcat and asb, it failed at : `TASK [ansible-service-broker CR state=present]`
clusterversion: `4.0.0-0.nightly-2019-02-12-005016`

````
ansible-playbook playbook.yml -vvv
.....
TASK [ansible-service-broker CR state=present] ***************************************************************************************************
task path: /home/zitang/project/catbrokers4/playbook.yml:115
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: zitang
<127.0.0.1> EXEC /bin/sh -c 'echo ~zitang && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176 `" && echo ansible-tmp-1549963951.36-214249263608176="` echo /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /home/zitang/.ansible/tmp/ansible-local-12412jsmLxx/tmpX0cDLW TO /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/ /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py", line 113, in <module>
    _ansiballz_main()
  File "/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_k8s_payload_tSdOVb/__main__.py", line 171, in <module>
  File "/tmp/ansible_k8s_payload_tSdOVb/__main__.py", line 167, in main
  File "/tmp/ansible_k8s_payload_tSdOVb/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 96, in execute_module
  File "/tmp/ansible_k8s_payload_tSdOVb/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py", line 190, in find_resource
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 612, in get
    results = self.search(**kwargs)
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 641, in search
    self.__client.invalidate_cache()
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 123, in invalidate_cache
    self.__init_cache(refresh=True)
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 113, in __init_cache
    self.__resources.update(self.parse_api_groups())
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 169, in parse_api_groups
    new_group[version] = self.get_resources_for_api_version(prefix, group['name'], version, preferred)
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 181, in get_resources_for_api_version
    resources_response = load_json(self.request('GET', path))['resources']
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 363, in request
    _return_http_data_only=params.get('_return_http_data_only', True)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 12 Feb 2019 09:32:43 GMT', 'Content-Length': '84', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})
HTTP response body: {
  "paths": [
    "/apis",
    "/metrics",
    "/swagger-ui/",
    "/version"
  ]
}

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/zitang/.ansible/tmp/ansible-tmp-1549963951.36-214249263608176/AnsiballZ_k8s.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_k8s_payload_tSdOVb/__main__.py\", line 171, in <module>\n  File \"/tmp/ansible_k8s_payload_tSdOVb/__main__.py\", line 167, in main\n  File \"/tmp/ansible_k8s_payload_tSdOVb/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 96, in execute_module\n  File \"/tmp/ansible_k8s_payload_tSdOVb/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py\", line 190, in find_resource\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 612, in get\n    results = self.search(**kwargs)\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 641, in search\n    self.__client.invalidate_cache()\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 123, in invalidate_cache\n    self.__init_cache(refresh=True)\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 113, in __init_cache\n    self.__resources.update(self.parse_api_groups())\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 169, in parse_api_groups\n    new_group[version] = self.get_resources_for_api_version(prefix, group['name'], version, preferred)\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 181, in get_resources_for_api_version\n    resources_response = load_json(self.request('GET', path))['resources']\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 363, in request\n    _return_http_data_only=params.get('_return_http_data_only', True)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 155, in __call_api\n    _request_timeout=_request_timeout)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 342, in request\n    headers=headers)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 231, in GET\n    query_params=query_params)\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 222, in request\n    raise ApiException(http_resp=r)\nkubernetes.client.rest.ApiException: (404)\nReason: Not Found\nHTTP response headers: HTTPHeaderDict({'Date': 'Tue, 12 Feb 2019 09:32:43 GMT', 'Content-Length': '84', 'Content-Type': 'application/json', 'Cache-Control': 'no-store'})\nHTTP response body: {\n  \"paths\": [\n    \"/apis\",\n    \"/metrics\",\n    \"/swagger-ui/\",\n    \"/version\"\n  ]\n}\n\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
	to retry, use: --limit @/home/zitang/project/catbrokers4/playbook.retry

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=12   changed=7    unreachable=0    failed=1   

````
no other special logs in the operator pod:
````
[core@ip-10-0-24-38 ~]$ oc get pod 
NAME                                          READY   STATUS    RESTARTS   AGE
automation-broker-operator-76765d974c-8h8c7   1/1     Running   0          32m
[core@ip-10-0-24-38 ~]$ oc get automationbroker
No resources found.
[core@ip-10-0-24-38 ~]$ oc logs -f automation-broker-operator-76765d974c-8h8c7
time="2019-02-12T09:34:02Z" level=info msg="Go Version: go1.10.3"
time="2019-02-12T09:34:02Z" level=info msg="Go OS/Arch: linux/amd64"
time="2019-02-12T09:34:02Z" level=info msg="Version of operator-sdk: v0.4.0+git"
time="2019-02-12T09:34:02Z" level=info msg="Watching openshift-ansible-service-broker namespace."
{"level":"info","ts":1549964042.6840196,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1549964042.849322,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1549964042.8606,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1549964042.861958,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1549964042.8623657,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"osb.openshift.io","Options.Version":"v1alpha1","Options.Kind":"AutomationBroker"}
{"level":"info","ts":1549964042.8625968,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"automationbroker-controller","source":"kind source: osb.openshift.io/v1alpha1, Kind=AutomationBroker"}
{"level":"info","ts":1549964042.963016,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"automationbroker-controller"}
{"level":"info","ts":1549964043.06328,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"automationbroker-controller","worker count":1}
````

**Comment by shawn-hurley** [comment]
It appears that you do not have access to the discovery endpoint. We have seen issues with the metrics.k8s.io aggregated API server basically blocking discovery. I would look more closely at the cluster.

**Comment by djzager** [comment]
A couple of things worth mentioning:

1) Previous [versions of the playbook](https://github.com/fusor/catbrokers4/commit/6b3f160e6b68f9db2aaf00fccb5ce359db924678#diff-2f78c4e27feaf25ffb33d97e8ff7e7a6) would fail to recognize that the `automationbrokers.osb.openshift.io` or `templateservicebrokers.osb.openshift.io` CRDs were missing. 
2) The playbook is idempotent, so if the CRD exists and the operator is running properly, you can run the playbook again.

**Comment by zihantang-rh** [comment]
@shawn-hurley @djzager thanks, I run the playbook again, and didn't hit this.
